-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.agreement
(
    id uuid NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    reference text COLLATE pg_catalog."default" NOT NULL,
    state text COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::text,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    deleted_at timestamp without time zone,
    CONSTRAINT "PK_e7537188219eeef56233a609753" PRIMARY KEY (id),
    CONSTRAINT "UQ_79e5037ff5f7838bdd2564bc025" UNIQUE (reference)
);

CREATE TABLE IF NOT EXISTS public.api_key
(
    id uuid NOT NULL,
    key_hash text COLLATE pg_catalog."default" NOT NULL,
    prefix text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    state text COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::text,
    agreement_id uuid NOT NULL,
    created_by uuid NOT NULL,
    profile_id uuid NOT NULL,
    expires_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    deleted_at timestamp without time zone,
    CONSTRAINT "PK_b1bd840641b8acbaad89c3d8d11" PRIMARY KEY (id),
    CONSTRAINT "UQ_3c9751d2a6011ba13e27838105e" UNIQUE (key_hash)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id uuid NOT NULL,
    resource text COLLATE pg_catalog."default" NOT NULL,
    action text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_a7f146f631691c4a595af1dbf89" PRIMARY KEY (id),
    CONSTRAINT "UQ_b5905e41a210003850c13f7c531" UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_profile
(
    id uuid NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_4339c2a4f958dfe3b3b38eb09d9" PRIMARY KEY (id),
    CONSTRAINT "UQ_7334dcd652fce6b9f6a1eb1bf6f" UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_refresh_token
(
    id uuid NOT NULL,
    token_hash text COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    user_id uuid NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_57203170666c2ed599635e17a81" PRIMARY KEY (id),
    CONSTRAINT "UQ_bf1dd91ca7309af8ec637fb1771" UNIQUE (token_hash)
);

CREATE TABLE IF NOT EXISTS public.auth_user
(
    id uuid NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    state text COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::text,
    agreement_id uuid NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    deleted_at timestamp without time zone,
    CONSTRAINT "PK_9922406dc7d70e20423aeffadf3" PRIMARY KEY (id),
    CONSTRAINT "UQ_3d29d788cd69d1ddf87e88e01eb" UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.bank_account
(
    id uuid NOT NULL,
    reference text COLLATE pg_catalog."default" NOT NULL,
    type text COLLATE pg_catalog."default" NOT NULL,
    balance integer NOT NULL DEFAULT 0,
    state text COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::text,
    agreement_id uuid NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    deleted_at timestamp without time zone,
    CONSTRAINT "PK_f3246deb6b79123482c6adb9745" PRIMARY KEY (id),
    CONSTRAINT "UQ_0704d5ba9d3eb8f8f39d1163372" UNIQUE (reference)
);

CREATE TABLE IF NOT EXISTS public.conciliation_matches
(
    id uuid NOT NULL,
    conciliation_id uuid NOT NULL,
    internal_tx_id uuid NOT NULL,
    external_tx_id uuid,
    status character varying COLLATE pg_catalog."default" NOT NULL,
    amount_diff integer NOT NULL DEFAULT 0,
    notes text COLLATE pg_catalog."default",
    CONSTRAINT "PK_23727177a6a50dc6f4aee6414ef" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.conciliations
(
    id uuid NOT NULL,
    run_at timestamp without time zone NOT NULL DEFAULT now(),
    status character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    summary jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT "PK_e89a0f59f2ef263995783d21892" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id uuid NOT NULL,
    customer_name text COLLATE pg_catalog."default" NOT NULL,
    amount integer NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.profile_permission
(
    profile_id uuid NOT NULL,
    permission_id uuid NOT NULL,
    CONSTRAINT "PK_9dedbb312c744c2e5952069d82f" PRIMARY KEY (profile_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.transaction
(
    id uuid NOT NULL,
    amount integer,
    operation text COLLATE pg_catalog."default" NOT NULL,
    type text COLLATE pg_catalog."default",
    state text COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::text,
    description text COLLATE pg_catalog."default" NOT NULL,
    bank_account_id uuid NOT NULL,
    correlation_id uuid,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    deleted_at timestamp without time zone,
    source_bank character varying(10) COLLATE pg_catalog."default" NOT NULL DEFAULT 'bank_a'::character varying,
    CONSTRAINT "PK_89eadb93a89810556e1cbcd6ab9" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.typeorm_migrations
(
    id serial NOT NULL,
    "timestamp" bigint NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_bb2f075707dd300ba86d0208923" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_profile
(
    user_id uuid NOT NULL,
    profile_id uuid NOT NULL,
    CONSTRAINT "PK_8fc18abbd305b736a80a19820a7" PRIMARY KEY (user_id, profile_id)
);

ALTER TABLE IF EXISTS public.api_key
    ADD CONSTRAINT "FK_2c6807ea1875aed696eb1754ded" FOREIGN KEY (agreement_id)
    REFERENCES public.agreement (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.api_key
    ADD CONSTRAINT "FK_3e1a593826fdc167686c7e84e39" FOREIGN KEY (profile_id)
    REFERENCES public.auth_profile (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.api_key
    ADD CONSTRAINT "FK_799ab142170befb4f010216e2e7" FOREIGN KEY (created_by)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.auth_refresh_token
    ADD CONSTRAINT "FK_d37ea24b7f4fe79c6f60203bdda" FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.auth_user
    ADD CONSTRAINT "FK_3af9328198d60ee191f271ee7bd" FOREIGN KEY (agreement_id)
    REFERENCES public.agreement (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.bank_account
    ADD CONSTRAINT "FK_842b5216a0e7f04584da2031a7e" FOREIGN KEY (agreement_id)
    REFERENCES public.agreement (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.conciliation_matches
    ADD CONSTRAINT "FK_conciliation_matches_conciliation" FOREIGN KEY (conciliation_id)
    REFERENCES public.conciliations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.profile_permission
    ADD CONSTRAINT "FK_3f7a714d3d16885bb32b1af14af" FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.profile_permission
    ADD CONSTRAINT "FK_f987696ae26dd9e18ef76f5235c" FOREIGN KEY (profile_id)
    REFERENCES public.auth_profile (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.transaction
    ADD CONSTRAINT "FK_0e11e3ea888c44f875201ece2ec" FOREIGN KEY (bank_account_id)
    REFERENCES public.bank_account (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.user_profile
    ADD CONSTRAINT "FK_8c154faf15b98f494723d9cc45b" FOREIGN KEY (profile_id)
    REFERENCES public.auth_profile (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_profile
    ADD CONSTRAINT "FK_eee360f3bff24af1b6890765201" FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;